### PR TITLE
numerical enhancement for lopexp transformation

### PR DESCRIPTION
**Pull request by zhenwendai**
replace exp(x)-1 with expm1(x).

### CODE REVIEW

**Comment by mzwiessele** [comment]
Can you remind me what this was about and why the tests are failing?

**Comment by zhenwendai** [comment]
It is simply to replace exp(x) -1 with expm1(x).

The tests fails because of an irrelevant setting problem on Mac.

python setup.py develop

Maybe try:

brew install pandoc

See http://johnmacfarlane.net/pandoc/installing.html

for installation options

---

Traceback (most recent call last):

File "setup.py", line 56, in <module>

desc = read_to_rst('README.md')

File "setup.py", line 48, in read_to_rst

pypandoc.convert(read(fname), 'rst', format='md', outputfile=rstname)

File 
"/Users/travis/install/Miniconda-latest-MacOSX-x86_64-2.7/lib/python2.7/site-packages/pypandoc/**init**.py", 
line 50, in convert

outputfile=outputfile, filters=filters)

File 
"/Users/travis/install/Miniconda-latest-MacOSX-x86_64-2.7/lib/python2.7/site-packages/pypandoc/**init**.py", 
line 70, in _convert

from_formats, to_formats = get_pandoc_formats()

File 
"/Users/travis/install/Miniconda-latest-MacOSX-x86_64-2.7/lib/python2.7/site-packages/pypandoc/**init**.py", 
line 197, in get_pandoc_formats

_ensure_pandoc_path()

File 
"/Users/travis/install/Miniconda-latest-MacOSX-x86_64-2.7/lib/python2.7/site-packages/pypandoc/**init**.py", 
line 336, in _ensure_pandoc_path

raise OSError("No pandoc was found: either install pandoc and add it\n"

OSError: No pandoc was found: either install pandoc and add it

to your PATH or install pypandoc wheels with included pandoc.

**Comment by mzwiessele** [comment]
This has been fixed a long long time ago, can you just merge in the current master?

**Comment by zhenwendai** [comment]
Done with the merge.

**Pull request merged**
