### PR TITLE
add the support for Adam from climin

### PR DESCRIPTION
**Pull request by zhenwendai**

### CODE REVIEW

**Comment by mzwiessele** [comment]
Nice, looks good!

Do we have the ability to add a test case to the optimization?

**Comment by mzwiessele** [comment]
The tests for the optimization routines are in parameterized tests, we should add one for adam, too, if possible.

**Comment by zhenwendai** [comment]
Sure. I did not notice there are testcases for optimizer. I will add one for adam.

**Comment by zhenwendai** [comment]
I just added a test case. Does it look alright now?

**Comment by mzwiessele** [comment]
Yes thanks!

**Pull request merged**
